### ISSUE TITLE
roles/dcm/vars/secrets.yml was not found

### ISSUE THREAD

**Issue by pdurbin** [sbgrid/data-capture-module#14]
I just ran `vagrant up` on 4eea1af and saw this error:

```
ERROR! vars file roles/dcm/vars/secrets.yml was not found
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I know to use ansible/roles/dcm/vars/secrets.yml.template as a starting point but this should probably mentioned in the README.

**Comment by pameyer** [comment]
Improvements to installation docs; linked to in README.
