### ISSUE TITLE
ur.py should return JSON

### ISSUE THREAD

**Issue by pdurbin** [sbgrid/data-capture-module#19]
When I stubbed out ur.py at https://github.com/sbgrid/data-capture-module/blob/9def4d8abc4aa63292473b8d04f2315b5c592cbc/api/dcm.py#L13 I assumed it would return JSON and wrote the code on the Dataverse side to expect JSON rather than a String.

Also, https://github.com/sbgrid/data-capture-module/blob/master/doc/api.md#generate-transfer-script doesn't specify what to expect as a response.

**Comment by pameyer** [comment]
56d680dc89f521183b53c07f19d035395d1a3b7a
