### ISSUE TITLE
compare ints

### ISSUE THREAD

**Issue by pdurbin** [sbgrid/data-capture-module#20]
In ur.py we need to change

    if req['datasetIdentifier'] != uid:

to

    if int(req['datasetIdentifier']) != int(uid):

to avoid a 500 error when calling sr.py

**Comment by pdurbin** [comment]
While you're in there,

- Explain that "uid" is "upload id" rather than "user id"
- Document `/deposit/processed` directory and what it is. It's metadata about the script, such as the dataset id and the user id on the Dataverse side.

**Comment by pameyer** [comment]
efecac28ed940548d469c1c2c9b7730916360b96 should have the fixes now.

**Comment by pdurbin** [comment]
I'm pretty sure we need 39db3b6 so I pushed it.

**Comment by pdurbin** [comment]
I was getting a 500 error without it.

**Comment by pdurbin** [comment]
@pameyer if you feel like we can safely close this issue after I pushed 39db3b6 to master, please go ahead.
