### ISSUE TITLE
script instructions should match those from dataverse

### ISSUE THREAD

**Issue by pameyer** [sbgrid/data-capture-module#24]
slight inconsistency in wording with instructional text from transfer scripts and and instructional text from dataverse was identified during https://github.com/IQSS/dataverse/issues/3998.

Issue here: change the text to finalized wording

**Comment by dlmurphy** [comment]
Rewritten text for the transfer scripts:

> DATAVERSE FILE UPLOAD SCRIPT
> Please enter the full path of the directory containing data files to upload for dataset number: ____
> Make sure your data is stored under this single directory. All files within this directory and its subdirectories will be uploaded to your dataset.

Note: I added the "DATAVERSE FILE UPLOAD SCRIPT" line as a title of sorts to orient the user that they are now running this script. I changed some of the wording in line 3, and also changed the wording in the instructions on Dataverse to match.
